version: '3'

services:
  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000
    links:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
