default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 0.0.0.0
  username: postgres
  password: root

development:
  <<: *default
  database: invest_calc_development

test:
  <<: *default
  database: invest_calc_test

production:
  <<: *default
  database: invest_calc_production
